//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomReservation()
        {
            this.RoomReservationDetails = new HashSet<RoomReservationDetail>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateEnded { get; set; }
        public int RoomId { get; set; }
        public Nullable<int> BillId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Bill Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationDetail> RoomReservationDetails { get; set; }
        public float Amount()
        {
            float _amount = (Int32.Parse(Room.RoomType.Amount));
            if (RoomReservationDetails.Count >= 3)
            {
                _amount *= 1.25f;
            }
            foreach (var detail in RoomReservationDetails)
            {
                if (detail.Customer.CustomerTypeId == 1)
                {
                    _amount *= 1.5f;
                    break;
                }
            }

            return _amount;
        }
    }
}
